version: '3'
services:
  myappdb:
    image: "postgres:latest"
    container_name: myappdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: myappdb
      POSTGRES_PASSWORD: abc123
      POSTGRES_DB: minisplitwise
    ports:
      - 5432:5432
    networks:
      - my-network
  
  frontend:
    image: chinx23/frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - my-network
  
  
  backend:
    image: chinx23/backend:latest
    ports:
      - "8081:8081"
    depends_on:
      - myappdb
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://myappdb:5432/minisplitwise?createDatabaseIfNotExist=true
    volumes:
      - logs-for-elk:/logs
    networks: 
      - my-network

  filebeat:
      image: elastic/filebeat:7.17.2
      volumes:
        - logs-for-el:/var/log/backend-container/ # Adjust this based on your actual log volume
      depends_on:
        - backend # Ensure Filebeat starts after your backend container
      environment:
        FILEBEAT_INPUTS: /var/log/backend-container/*.log # Specify your log file paths
        FILEBEAT_OUTPUT_ELASTICSEARCH_HOSTS: "https://spe-majorproject.es.asia-south1.gcp.elastic-cloud.com" # Replace with your Elasticsearch host(s) and port
        FILEBEAT_OUTPUT_ELASTICSEARCH_USERNAME: "elastic" # Set username for Elasticsearch access
        FILEBEAT_OUTPUT_ELASTICSEARCH_PASSWORD: "SPEmajorproject123" # Secure your password!
volumes:
  postgres-data:
    driver: local
  logs-for-elk:
    driver: local
networks:
  my-network:
    driver: bridge
