spring:
  security:
    user:
      name: tejas
      password: ok
  datasource:
    url: jdbc:postgresql://localhost:5432/minisplitwise
    username: tejsharma
    password: tej123four
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port=5000:
